import { useEffect, useRef, useState } from 'react';
import './App.css';
import { EventsOn, EventsOff } from '../wailsjs/runtime/runtime';
const api = () => window.go?.main?.App;
function App() {
  const [form, setForm] = useState({ host: '', port: 22, username: '', password: '', privateKey: '', passphrase: '' }); const [authType, setAuthType] = useState('password'); const [connected, setConnected] = useState(false); const [status, setStatus] = useState('准备就绪'); const [terminal, setTerminal] = useState(''); const terminalRef = useRef(null); const inputRef = useRef(null);
  useEffect(() => { EventsOn('terminal-output', data => setTerminal(value => value + data)); EventsOn('terminal-status', message => { setStatus(message); setConnected(false); }); return () => { EventsOff('terminal-output'); EventsOff('terminal-status'); }; }, []);
  useEffect(() => { if (terminalRef.current) terminalRef.current.scrollTop = terminalRef.current.scrollHeight; }, [terminal]);
  const setField = (key, value) => setForm(current => ({ ...current, [key]: value })); const terminalSize = () => ({ columns: 100, rows: 30 });
  async function connect() { setStatus('正在建立安全连接…'); try { const payload = { ...form, port: Number(form.port), password: authType === 'password' ? form.password : '', privateKey: authType === 'key' ? form.privateKey : '' }; const message = await api().Connect(payload, terminalSize()); setTerminal(''); setConnected(true); setStatus(message); setTimeout(() => inputRef.current?.focus(), 50); } catch (error) { setStatus(`连接失败：${error}`); } }
  async function disconnect() { await api().Disconnect(); setConnected(false); setStatus('已断开连接'); }
  async function sendInput(event) { if (!connected) return; const keys = {ArrowUp:'\\x1b[A',ArrowDown:'\\x1b[B',ArrowLeft:'\\x1b[D',ArrowRight:'\\x1b[C',Backspace:'\\x7f',Enter:'\\r'}; const value = keys[event.key] || (event.key.length === 1 ? event.key : null); if (value) { event.preventDefault(); await api().SendInput(value); } }
  return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">›_</span><span>uSSH</span></div><div className="new-session"><span>新建会话</span><small>基础 SSH 终端</small></div><div className="sidebar-footer"><span className={connected ? 'dot online' : 'dot'}></span>{connected ? '已连接' : '未连接'}</div></aside><section className="workspace"><header><div><p className="eyebrow">SSH CLIENT</p><h1>新建连接</h1></div><div className="status"><span className={connected ? 'dot online' : 'dot'}></span>{status}</div></header><div className="content"><section className="card connection-card"><div className="card-title"><div><h2>连接信息</h2><p>使用密码或 PEM 私钥安全登录服务器</p></div></div><div className="fields"><label className="wide">主机地址<input value={form.host} onChange={e => setField('host', e.target.value)} placeholder="example.com 或 192.168.1.10" /></label><label>端口<input type="number" value={form.port} onChange={e => setField('port', e.target.value)} /></label><label>用户名<input value={form.username} onChange={e => setField('username', e.target.value)} placeholder="root" /></label></div><div className="auth-tabs"><button className={authType === 'password' ? 'active' : ''} onClick={() => setAuthType('password')}>密码</button><button className={authType === 'key' ? 'active' : ''} onClick={() => setAuthType('key')}>私钥</button></div>{authType === 'password' ? <label>密码<input type="password" value={form.password} onChange={e => setField('password', e.target.value)} placeholder="不会被保存" /></label> : <><label>PEM 私钥<textarea value={form.privateKey} onChange={e => setField('privateKey', e.target.value)} placeholder="-----BEGIN OPENSSH PRIVATE KEY-----" /></label><label>私钥密码（可选）<input type="password" value={form.passphrase} onChange={e => setField('passphrase', e.target.value)} /></label></>}<div className="actions"><button className="primary" onClick={connect} disabled={connected}>连接服务器 <span>→</span></button>{connected && <button className="secondary" onClick={disconnect}>断开</button>}<span className="security-note">初版将接受未知主机指纹</span></div></section><section className="terminal-wrap"><div className="terminal-header"><span className="traffic"><i></i><i></i><i></i></span><span>{connected ? `${form.username}@${form.host}` : '终端预览'}</span></div><pre className="terminal" ref={terminalRef} onClick={() => inputRef.current?.focus()}>{terminal || <span className="terminal-placeholder">连接服务器后，终端输出将显示在这里。</span>}</pre><input ref={inputRef} className="terminal-capture" onKeyDown={sendInput} disabled={!connected} aria-label="SSH terminal input" /></section></div></section></main>;
}
export default App;
