// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCredential(arg1) {
  return window['go']['main']['App']['ClearCredential'](arg1);
}

export function CloneSSHLink(arg1) {
  return window['go']['main']['App']['CloneSSHLink'](arg1);
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateSSHLink(arg1, arg2) {
  return window['go']['main']['App']['CreateSSHLink'](arg1, arg2);
}

export function DeleteSSHLink(arg1) {
  return window['go']['main']['App']['DeleteSSHLink'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function GetCredential(arg1) {
  return window['go']['main']['App']['GetCredential'](arg1);
}

export function ListConnectionNodes() {
  return window['go']['main']['App']['ListConnectionNodes']();
}

export function MoveNode(arg1, arg2) {
  return window['go']['main']['App']['MoveNode'](arg1, arg2);
}

export function PickPrivateKeyFile() {
  return window['go']['main']['App']['PickPrivateKeyFile']();
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SetCredential(arg1, arg2) {
  return window['go']['main']['App']['SetCredential'](arg1, arg2);
}

export function SetGpuAcceleration(arg1) {
  return window['go']['main']['App']['SetGpuAcceleration'](arg1);
}

export function UpdateSSHLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSSHLink'](arg1, arg2, arg3);
}
