// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ResizeTerminal(arg1) {
  return window['go']['main']['App']['ResizeTerminal'](arg1);
}

export function SendInput(arg1) {
  return window['go']['main']['App']['SendInput'](arg1);
}
