// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearCredential(arg1:number):Promise<void>;

export function Connect(arg1:string,arg2:main.ConnectionConfig,arg3:main.TerminalSize):Promise<string>;

export function CreateFolder(arg1:number,arg2:string):Promise<main.SavedNode>;

export function CreateSSHLink(arg1:number,arg2:main.SavedNode):Promise<main.SavedNode>;

export function DeleteSSHLink(arg1:number):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetCredential(arg1:number):Promise<main.CredentialView>;

export function ListConnectionNodes():Promise<Array<main.SavedNode>>;

export function MoveNode(arg1:number,arg2:number):Promise<main.SavedNode>;

export function PickPrivateKeyFile():Promise<string>;

export function ResizeTerminal(arg1:string,arg2:main.TerminalSize):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function SetCredential(arg1:number,arg2:main.SavedCredential):Promise<void>;

export function UpdateSSHLink(arg1:number,arg2:number,arg3:main.SavedNode):Promise<main.SavedNode>;
