// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.ConnectionConfig,arg2:main.TerminalSize):Promise<string>;

export function Disconnect():Promise<void>;

export function ResizeTerminal(arg1:main.TerminalSize):Promise<void>;

export function SendInput(arg1:string):Promise<void>;
