// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ClearCredential(arg1:number):Promise<void>;

export function CloneSSHLink(arg1:number):Promise<backend.SavedNode>;

export function Connect(arg1:string,arg2:backend.ConnectionConfig,arg3:backend.TerminalSize):Promise<string>;

export function CreateFolder(arg1:number,arg2:string,arg3:string):Promise<backend.SavedNode>;

export function CreateSSHLink(arg1:number,arg2:backend.SavedNode):Promise<backend.SavedNode>;

export function DeleteFolder(arg1:number):Promise<void>;

export function DeleteSSHLink(arg1:number):Promise<void>;

export function DeleteTerminalLog(arg1:string,arg2:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecRemoteCommand(arg1:string,arg2:string,arg3:number):Promise<backend.RemoteCommandResult>;

export function FetchModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetCredential(arg1:number):Promise<backend.CredentialView>;

export function GetLocalTerminalSettings():Promise<backend.LocalTerminalSettings>;

export function GetSystemInfo(arg1:string):Promise<backend.SystemInfo>;

export function GetTerminalLogSettings():Promise<backend.TerminalLogSettings>;

export function ListAvailableLocalTerminals():Promise<Array<backend.LocalTerminalOption>>;

export function ListAvailableTerminalFonts():Promise<Array<string>>;

export function ListConnectionNodes():Promise<Array<backend.SavedNode>>;

export function ListSftp(arg1:string,arg2:string):Promise<Array<backend.SftpEntry>>;

export function ListTerminalLogs(arg1:string):Promise<Array<backend.TerminalLogFile>>;

export function MoveNode(arg1:number,arg2:number):Promise<backend.SavedNode>;

export function PickDownloadDirectory():Promise<string>;

export function PickPrivateKeyFile():Promise<string>;

export function PickSavePath(arg1:string):Promise<string>;

export function PickTerminalLogDirectory():Promise<string>;

export function PickUploadFiles():Promise<Array<backend.LocalUploadFile>>;

export function ReadTerminalLog(arg1:string,arg2:string):Promise<backend.TerminalLogContent>;

export function ReorderNodes(arg1:number,arg2:Array<number>):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:backend.TerminalSize):Promise<void>;

export function ResolveApproval(arg1:string,arg2:string):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function SetBackdropType(arg1:string):Promise<void>;

export function SetCredential(arg1:number,arg2:backend.SavedCredential):Promise<void>;

export function SetGpuAcceleration(arg1:boolean):Promise<void>;

export function SetLocalTerminalSettings(arg1:backend.LocalTerminalSettings):Promise<void>;

export function SetTerminalLogSettings(arg1:backend.TerminalLogSettings):Promise<void>;

export function SftpDownload(arg1:string,arg2:string,arg3:string):Promise<number>;

export function SftpMkdir(arg1:string,arg2:string):Promise<void>;

export function SftpRead(arg1:string,arg2:string):Promise<backend.SftpFileInfo>;

export function SftpRemove(arg1:string,arg2:string):Promise<void>;

export function SftpRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpStat(arg1:string,arg2:string):Promise<backend.SftpEntry>;

export function SftpUpload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpWrite(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;

export function StartAIChat(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<backend.AIChatMessage>):Promise<void>;

export function StartAgent(arg1:backend.AgentRequest):Promise<void>;

export function StartLocalTerminal(arg1:string,arg2:backend.TerminalSize):Promise<string>;

export function StopAIChat(arg1:string):Promise<void>;

export function StopAgent(arg1:string):Promise<void>;

export function UpdateFolder(arg1:number,arg2:string,arg3:string):Promise<backend.SavedNode>;

export function UpdateSSHLink(arg1:number,arg2:number,arg3:backend.SavedNode):Promise<backend.SavedNode>;
